### ISSUE TITLE
Availability of the Journey Builder Developer's Guide

### ISSUE THREAD

**Issue by eljazouli** [sfmcdg/Salesforce-Marketing-Cloud-Developer-Edition-Recipes#4]
Hi contributors, 

I am always pleased to see this kind of initiatives around Salesforce Marketing Cloud so thank you !

I tried to look for the "Journey Builder Developer's Guide" book by Eliot Harper (one of the major contributors of this repo!) but I couldn't find it on sale anymore 😢 

Is there a way to find a pdf or paper version of this book on sale ? 

I am also certified Salesforce Marketing Cloud consultant and I can contribute to this repo if needed 😃 

Thank you so much for your great work ! 

Zak

**Comment by mattcam** [comment]
Hello Zak, thanks for positive feedback and offer to help contribute. Can you help with a pull request? Whilst doing prep for SFMC consultant exam did the [exam guide notes](https://github.com/eljazouli/Salesforce-Marketing-Cloud-Developer-Edition-Recipes#guides) - these could definitely do with another set of eyes to read over and update as required. I will also forward your request re book onto Eliot.

**Comment by eliotharper** [comment]
Hello @eljazouli, my book that you refer to is somewhat outdated now, as a result of several significant new updates to Journey Builder. However, the concepts still remain and the WDF documentation is still mostly relevant. You can download the book from http://digital-logic.s3.amazonaws.com/temp/isbn9780994311801.pdf

**Comment by jrcha** [comment]
Hi @eliotharper , the link above is not available anymore, would you be so kind to provide a new link ? I tried to buy your book in Amazon and it's not available.

Thank you!

**Comment by eliotharper** [comment]
Hello @jrcha, here is updated link: https://www.dropbox.com/s/ng07itj488zelbr/ISBN9780994311801.pdf?dl=0

**Comment by nenadatanasovski** [comment]
Thanks for sharing, @elliotharper. Are you planning to release an always-up-to-date online version similar to the Ampscript guide? Would be great to have working examples when building out custom activities.

**Comment by eliotharper** [comment]
Hi @nenadatanasovski, I'm considering this, but I'm waiting for development to level out, as it's still rapidly changing at the moment and will be hard to keep up-to-date.

**Comment by sproutward** [comment]
@eliotharper , thank you very much for the link. Would you provide a few bullet points of the things that outdate the book?

In particular, I am trying to understand the right way to use SFMC Journeys with an app. I have read through your Github recipes(https://github.com/sfmcdg/Salesforce-Marketing-Cloud-Developer-Edition-Recipes/blob/master/firing-events.md)

Currently, I am using dataEvents to upsert data to a DE. Are dataEvents interchangeable with contactEvents? Can the same behavior available thru contactEvents be accomplished upserting columns in a DE as event columns using dataEvents? Do you know any resources available with recipes and best practices?

**Comment by eliotharper** [comment]
@sproutward, DataEvents are quite different from ContactEvents. You can schedule a [free] call with me at [eliot.com.au](https://eliot.com.au) and we can review your use case together and I will explain the best approach for you.

**Comment by Adricz22** [comment]
Hello @sfmcdg 👋

# 🌍 Top International Developer Events

Discover the **most influential tech conferences and developer events** happening around the world.  
Connect, learn, and grow with the **global developer community**.

---

## 🚀 Why Join?
- 🔴 **Live Events** – Stay updated with the latest happenings in tech  
- 🌐 **Global Community** – Network with developers from all continents  
- 📅 **Updated Daily** – Fresh events, always current  
- 🏆 **Top 10 Developer Events** – Hand-picked to shape the future of technology  

From **cutting-edge frameworks** to **emerging paradigms**, we bring you the opportunities that matter.

---

## 🔑 Get Started  
**[➡️ Continue with GitHub](https://www.globaldevsummit.com/)**  
🔒 **Connect securely** • Save favorites • Get personalized recommendations  

---

## 📌 Highlights
- Meet industry leaders and tech innovators  
- Join exclusive technical workshops  
- Explore new frameworks, tools, and best practices  
- Grow your personal and professional network  

---

> 📢 **Tip:** Bookmark the page and check daily for new opportunities.  
Your next big career move could start here!

---
